
CREATE DATABASE IF NOT EXISTS movie_ticket_system
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;
USE movie_ticket_system;

CREATE TABLE Roles(
 RoleID INT AUTO_INCREMENT PRIMARY KEY,
 RoleName VARCHAR(50) NOT NULL UNIQUE,
 Description VARCHAR(255)
)ENGINE=InnoDB;

CREATE TABLE Users(
 UserID INT AUTO_INCREMENT PRIMARY KEY,
 RoleID INT NOT NULL,
 Username VARCHAR(50) NOT NULL UNIQUE,
 PasswordHash VARCHAR(255) NOT NULL,
 Email VARCHAR(100) NOT NULL UNIQUE,
 Phone VARCHAR(20) UNIQUE,
 FullName VARCHAR(100) NOT NULL,
 AvatarURL VARCHAR(255),
 Status ENUM('Active','Inactive','Banned') DEFAULT 'Active',
 CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
 UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 CONSTRAINT fk_users_role FOREIGN KEY(RoleID) REFERENCES Roles(RoleID)
);

CREATE TABLE UserRoles(
 UserID INT,
 RoleID INT,
 CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
 UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 PRIMARY KEY(UserID,RoleID),
 FOREIGN KEY(UserID) REFERENCES Users(UserID),
 FOREIGN KEY(RoleID) REFERENCES Roles(RoleID)
);

CREATE TABLE Movies(
 MovieID INT AUTO_INCREMENT PRIMARY KEY,
 Title VARCHAR(255) NOT NULL,
 Description TEXT,
 DurationMinutes INT NOT NULL,
 ReleaseDate DATE NOT NULL,
 Language VARCHAR(50),
 Director VARCHAR(100),
 MovieCast TEXT,
 PosterURL VARCHAR(255),
 TrailerURL VARCHAR(255),
 Status ENUM('Coming Soon','Now Showing','Ended') DEFAULT 'Coming Soon',
 CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
 UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE Genres(
 GenreID INT AUTO_INCREMENT PRIMARY KEY,
 Name VARCHAR(100) UNIQUE NOT NULL,
 Description TEXT,
 CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
 UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE Movie_Genres(
 MovieID INT,
 GenreID INT,
 PRIMARY KEY(MovieID,GenreID),
 FOREIGN KEY(MovieID) REFERENCES Movies(MovieID),
 FOREIGN KEY(GenreID) REFERENCES Genres(GenreID)
);

CREATE TABLE Cinemas(
 CinemaID INT AUTO_INCREMENT PRIMARY KEY,
 Name VARCHAR(100) NOT NULL,
 Address VARCHAR(255) NOT NULL,
 City VARCHAR(100) NOT NULL,
 Phone VARCHAR(20),
 Email VARCHAR(100),
 CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
 UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE Halls(
 HallID INT AUTO_INCREMENT PRIMARY KEY,
 CinemaID INT NOT NULL,
 Name VARCHAR(50) NOT NULL,
 Type ENUM('2D','3D','IMAX','4DX') DEFAULT '2D',
 Capacity INT NOT NULL,
 CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
 UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 FOREIGN KEY(CinemaID) REFERENCES Cinemas(CinemaID)
);

CREATE TABLE Seats(
 SeatID INT AUTO_INCREMENT PRIMARY KEY,
 HallID INT NOT NULL,
 SeatRow VARCHAR(5) NOT NULL,
 Number INT NOT NULL,
 Type ENUM('Standard','VIP','Couple') DEFAULT 'Standard',
 PriceMultiplier DECIMAL(3,2) DEFAULT 1.00,
 CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
 UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 UNIQUE(HallID,SeatRow,Number),
 FOREIGN KEY(HallID) REFERENCES Halls(HallID)
);

CREATE TABLE Showtimes(
 ShowtimeID INT AUTO_INCREMENT PRIMARY KEY,
 MovieID INT NOT NULL,
 HallID INT NOT NULL,
 StartTime DATETIME NOT NULL,
 EndTime DATETIME NOT NULL,
 BasePrice DECIMAL(10,2) NOT NULL,
 Status ENUM('Scheduled','Ongoing','Completed','Cancelled') DEFAULT 'Scheduled',
 CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
 UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 FOREIGN KEY(MovieID) REFERENCES Movies(MovieID),
 FOREIGN KEY(HallID) REFERENCES Halls(HallID)
);

CREATE TABLE Showtime_Seats(
 ShowtimeSeatID INT AUTO_INCREMENT PRIMARY KEY,
 ShowtimeID INT NOT NULL,
 SeatID INT NOT NULL,
 Price DECIMAL(10,2) NOT NULL,
 Status ENUM('Available','Reserved','Booked') DEFAULT 'Available',
 UNIQUE(ShowtimeID,SeatID),
 FOREIGN KEY(ShowtimeID) REFERENCES Showtimes(ShowtimeID),
 FOREIGN KEY(SeatID) REFERENCES Seats(SeatID)
);

CREATE TABLE Coupons(
 CouponID INT AUTO_INCREMENT PRIMARY KEY,
 Code VARCHAR(50) UNIQUE NOT NULL,
 DiscountType ENUM('Percentage','Fixed Amount') NOT NULL,
 DiscountValue DECIMAL(10,2) NOT NULL,
 ExpiryDate DATETIME NOT NULL,
 UsageLimit INT DEFAULT 100,
 UsageCount INT DEFAULT 0,
 IsActive BOOLEAN DEFAULT TRUE,
 CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
 UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE Bookings(
 BookingID INT AUTO_INCREMENT PRIMARY KEY,
 UserID INT NOT NULL,
 ShowtimeID INT NOT NULL,
 CouponID INT NULL,
 BookingDate DATETIME DEFAULT CURRENT_TIMESTAMP,
 Status ENUM('Pending','Confirmed','Cancelled','Refunded') DEFAULT 'Pending',
 TotalAmount DECIMAL(10,2) NOT NULL,
 CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
 UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 FOREIGN KEY(UserID) REFERENCES Users(UserID),
 FOREIGN KEY(ShowtimeID) REFERENCES Showtimes(ShowtimeID),
 FOREIGN KEY(CouponID) REFERENCES Coupons(CouponID)
);

CREATE TABLE Tickets(
 TicketID INT AUTO_INCREMENT PRIMARY KEY,
 BookingID INT NOT NULL,
 ShowtimeSeatID INT NOT NULL,
 Price DECIMAL(10,2) NOT NULL,
 CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(BookingID) REFERENCES Bookings(BookingID),
 FOREIGN KEY(ShowtimeSeatID) REFERENCES Showtime_Seats(ShowtimeSeatID)
);

CREATE TABLE Payments(
 PaymentID INT AUTO_INCREMENT PRIMARY KEY,
 BookingID INT NOT NULL,
 Amount DECIMAL(10,2) NOT NULL,
 PaymentMethod ENUM('Credit Card','Momo','ZaloPay','Cash') NOT NULL,
 Status ENUM('Pending','Success','Failed','Refunded') DEFAULT 'Pending',
 TransactionID VARCHAR(100),
 CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
 UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 FOREIGN KEY(BookingID) REFERENCES Bookings(BookingID)
);

CREATE TABLE Reviews(
 ReviewID INT AUTO_INCREMENT PRIMARY KEY,
 UserID INT NOT NULL,
 MovieID INT NOT NULL,
 Rating TINYINT NOT NULL,
 Comment TEXT,
 CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
 UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 FOREIGN KEY(UserID) REFERENCES Users(UserID),
 FOREIGN KEY(MovieID) REFERENCES Movies(MovieID)
);

CREATE TABLE Notifications(
 NotificationID INT AUTO_INCREMENT PRIMARY KEY,
 UserID INT NOT NULL,
 Type ENUM('System','Promotion','Booking') NOT NULL,
 Content TEXT NOT NULL,
 IsRead BOOLEAN DEFAULT FALSE,
 CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(UserID) REFERENCES Users(UserID)
);
